services:
  nginx:
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app
      - traefik
    labels:
      - traefik.enable=true
      - traefik.docker.network=${TRAEFIK_NETWORK}
      - traefik.http.routers.php-smarty-blog.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.php-smarty-blog.entrypoints=${TRAEFIK_ENTRYPOINT}
      - traefik.http.services.php-smarty-blog.loadbalancer.server.port=80

  php:
    build:
      target: dev
    volumes:
      - ./:/var/www/html

  mysql:
    ports:
      - "3306:3306"

networks:
  traefik:
    name: ${TRAEFIK_NETWORK:-traefik}
    external: true
